### ISSUE TITLE
deploy docs missing 404

### ISSUE THREAD

**Issue by MareoRaft** [analythium/shinyproxy-1-click#4]
The instructions for ShinyProxy droplet on DigitalOcean include a link to documentation for deployment.  The URL of this link is https://shinyproxy.io/deploying-apps/ .  I have also included a picture at the bottom of this post where you can see the link "deploy your Shiny apps" in the DO docs.

The webpage is missing.  Clicking the link results in a 404 error.

  1. Can you fix the link and/or the server so that clicking the link brings me to the deployment documentation?
  2. Can you also provide a working link to the deployment docs here, for reference?

<img width="749" alt="Schermata 2021-04-05 alle 11 23 03 AM" src="https://user-images.githubusercontent.com/860303/113591037-6b0bc800-9601-11eb-8f6b-0d03a58a6269.png">

**Comment by psolymos** [comment]
Hi @MareoRaft thanks for the report on the broken link. The shinyproxy website has been recently revamped, so I'll need to check all the links.

I am planning to update the 1-click image, see #3 . I'll include updated links in the summary.

**Comment by psolymos** [comment]
@MareoRaft The new posting for v2.5.0 is out and the links fixed: https://marketplace.digitalocean.com/apps/shinyproxy
