### ISSUE TITLE
can this be used as reverse proxy?

### ISSUE THREAD

**Issue by IAmBlackat** [analythium/shinyproxy-1-click#6]
Is this an reverse proxy or usable as reverse proxy?

**Comment by psolymos** [comment]
You can look at it that way, but this 1-click image includes Nginx and ShinyProxy. If you only want the proxy capabilities, check out ContainerProxy that is the foundation for ShinyProxy: https://github.com/openanalytics/containerproxy. Hope this helps.

**Comment by IAmBlackat** [comment]
thank you for clarification.
