### ISSUE TITLE
Upload size restrictions

### ISSUE THREAD

**Issue by rhngla** [analythium/shinyproxy-1-click#7]
I deployed a shiny app using [digital ocean droplet with shinyproxy 1-click](https://marketplace.digitalocean.com/apps/shinyproxy) with the following software versions:
```
ShinyProxy        2.6.0
OpenJD            11.0.11
Docker CE         20.10.7
Docker Compose    1.25.0
Nginx             1.18.0
```
I cannot upload larger data files (~100 Mb) to my shiny app. The error message appears within the shiny app:

```html
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
```
 - I confirmed that docker and the shiny components both allow large file uploads to the app.
 - I also see that an earlier version of shinyproxy [removed restrictions on file upload size](https://shinyproxy.io/faq/#uploading-big-files-does-not-work).
 - Following [this suggestion](https://stackoverflow.com/questions/28476643/default-nginx-client-max-body-size), I tried modifying `/etc/nginx/nginx.conf` to set `client_max_body_size` parameter, but this did not work.
 
Are there any other configuration files I should modify?

**Comment by rhngla** [comment]
Solved! I followed the [setup instructions](https://github.com/analythium/shinyproxy-1-click/blob/master/digitalocean/setup.md) and realized the nginx config file is `/etc/nginx/sites-enabled/default`.

Setting `client_max_body_size` in `/etc/nginx/sites-enabled/default` to the appropriate file size enabled large file uploads (The default was 20M).
```
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        ## Add here your custom domain
        # server_name example.com www.example.com;
        server_name _;

        location / {
            proxy_pass          http://127.0.0.1:8080/;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 600s;

            proxy_redirect    off;
            proxy_set_header  Host             $http_host;
            proxy_set_header  X-Real-IP        $remote_addr;
            proxy_set_header  X-Forwarded-For  $proxy_add_x_forwarded_for;
            proxy_set_header  X-Forwarded-Protocol $scheme;
        }

        ## Set here max file size
        client_max_body_size 600M;
}
```

**Comment by psolymos** [comment]
@rhngla: I am glad that the instructions were helpful. Thanks for the nice summary that can help others too.
