### ISSUE TITLE
Updating shinyproxy

### ISSUE THREAD

**Issue by EydlinIlya** [analythium/shinyproxy-1-click#8]
Thank you for the incredible droplet! 
I would like to update shinyproxy from 2.5 to 3.0. Is it possible to do it on the 1-click app? Is it enough to simply replace the shinyproxy.jar file in the /opt/shinyproxy and restart the machine?

**Comment by psolymos** [comment]
Yes, that should be fine as long as you watch the owner. Might be easier to install:

```
export VERSION="3.1.0"
sudo wget https://www.shinyproxy.io/downloads/shinyproxy_${VERSION}_amd64.deb
sudo apt install ./shinyproxy_${VERSION}_amd64.deb
```

Then `service shinyproxy restart` - you don't have to restart the droplet.
